name: CI
on:
  workflow_dispatch:
    inputs:
      tests:
        description: "What tests to run. Available options: rejson, rts, redisearch, redisgraph, redisgears, redisbloom, rebloomTopK, rebloomCMK, rebloomCuckoo. Use 'All' to run all tests."
        required: true
        default: 'All'
      #rejson:
      #  description: 'Run ReJSON tests'
      #  required: true
      #  default: 'Yes'
      #rts:
      #  description: 'Run RTS tests'
      #  required: true
      #  default: 'Yes'
      #redisearch:
      #  description: 'Run RediSearch tests'
      #  required: true
      #  default: 'Yes'
      #redisgraph:
      #  description: 'Run RedisGraph tests'
      #  required: true
      #  default: 'Yes'
      #redisgears:
      #  description: 'Run RedisGears tests'
      #  required: true
      #  default: 'Yes'
      #redisbloom:
      #  description: 'Run RedisBloom tests'
      #  required: true
      #  default: 'Yes'
      #redisbloomtopk:
      #  description: 'Run RedisBloom TopK tests'
      #  required: true
      #  default: 'Yes'
      #redisbloomcmk:
      #  description: 'Run RedisBloom CMK tests'
      #  required: true
      #  default: 'Yes'
      #redisbloomcuckoo:
      #  description: 'Run RedisBloom Cuckoo tests'
      #  required: true
      #  default: 'Yes'
  pull_request: 
    branches: [master]
jobs:
  #Verifying build and compilation
  Setup:
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.files.outputs.all }}
      rejson-selected: ${{(github.event_name == 'workflow_dispatch' && (contains(github.event.inputs.tests, 'rejson') || github.event.inputs.tests == 'All'))}}
      rejson-changes: ${{github.event_name == 'pull_request' && contains(steps.files.outputs.all, 'rejson.ts')}}
    steps:
      - if: github.event_name == 'workflow_dispatch'
      - uses: actions/checkout@v2
      - id: files
        uses: jitterbit/get-changed-files@v1
      - run: "echo ${{ steps.files.outputs.all }}"
  Compilation:
    runs-on: ubuntu-latest
    needs: Setup
    steps:
    - uses: actions/checkout@v2
    - run: "echo ${{ needs.Setup.outputs.files }}"
    - name: Setup & build
      run: npm i && npm run build
  #Build for 'ReJSON' module
  ReJSON:
    needs: Setup
    if: needs.Setup.outputs.rejson-selected || needs.Setup.outputs.rejson-changes
    runs-on: ubuntu-latest
    steps:
    - uses: docker-practice/actions-setup-docker@master
      with:
        docker_channel: nightly
        docker_nightly_version: snapshot-20200915
    - uses: actions/checkout@v2
    - name: Setting up Redis
      run: docker run -p 6379:6379 -d --rm redislabs/rejson:latest && docker ps -a
    - name: Running tests
      run: npm i && npm run rejson-module-tests
  #Build for 'Redis Times Series' module
  RTS:
    needs: Setup
    if: (github.event_name == 'workflow_dispatch' && (contains(github.event.inputs.tests, 'rts') || github.event.inputs.tests == 'All')) || github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
    - uses: docker-practice/actions-setup-docker@master
      with:
        docker_channel: nightly
        docker_nightly_version: snapshot-20200915
    - uses: actions/checkout@v2
    - name: Setting up Redis
      run: docker run -p 6379:6379 -d --rm redislabs/redistimeseries && docker ps -a
    - name: Running tests
      run: npm i && npm run rts-module-tests
  #Build for 'Redis Search' module
  Redisearch:
    needs: Setup
    if: (github.event_name == 'workflow_dispatch' && (contains(github.event.inputs.tests, 'redisearch') || github.event.inputs.tests == 'All')) || github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
    - uses: docker-practice/actions-setup-docker@master
      with:
        docker_channel: nightly
        docker_nightly_version: snapshot-20200915
    - uses: actions/checkout@v2
    - name: Setting up Redis
      run: docker run -p 6379:6379 -d --rm redislabs/redisearch:latest && docker ps -a
    - name: Running tests
      run: npm i && npm run redisearch-module-tests
  #Build for 'Redis Graph module
  RedisGraph:
    needs: Setup
    if: (github.event_name == 'workflow_dispatch' && (contains(github.event.inputs.tests, 'redisgraph') || github.event.inputs.tests == 'All')) || github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
    - uses: docker-practice/actions-setup-docker@master
      with:
        docker_channel: nightly
        docker_nightly_version: snapshot-20200915
    - uses: actions/checkout@v2
    - name: Setting up Redis
      run: docker run -p 6379:6379 -d --rm redislabs/redisgraph:latest && docker ps -a
    - name: Running tests
      run: npm i && npm run redisgraph-module-tests
  #Build for 'RedisGears' module
  RedisGears:
    needs: Setup
    if: (github.event_name == 'workflow_dispatch' && (contains(github.event.inputs.tests, 'redisgears') || github.event.inputs.tests == 'All')) || github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
    - uses: docker-practice/actions-setup-docker@master
      with:
        docker_channel: nightly
        docker_nightly_version: snapshot-20200915
    - uses: actions/checkout@v2
    - name: Setting up Redis
      run: docker run -p 6379:6379 -d --rm redislabs/redisgears:latest && docker ps -a
    - name: Running tests
      run: npm i && npm run redisgears-module-tests
  #Build for 'Redis Bloom' module
  ReBloom:
    needs: Setup
    if: (github.event_name == 'workflow_dispatch' && (contains(github.event.inputs.tests, 'redisbloom') || github.event.inputs.tests == 'All')) || github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
    - uses: docker-practice/actions-setup-docker@master
      with:
        docker_channel: nightly
        docker_nightly_version: snapshot-20200915
    - uses: actions/checkout@v2
    - name: Setting up Redis
      run: docker run -p 6379:6379 -d --rm redislabs/rebloom:latest && docker ps -a
    - name: Running tests
      run: npm i && npm run redisbloom-filter-tests
  #Build for 'Redis Bloom TopK' filter
  ReBloomTopK:
    needs: Setup
    if: (github.event_name == 'workflow_dispatch' && (contains(github.event.inputs.tests, 'rebloomTopK') || github.event.inputs.tests == 'All')) || github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
    - uses: docker-practice/actions-setup-docker@master
      with:
        docker_channel: nightly
        docker_nightly_version: snapshot-20200915
    - uses: actions/checkout@v2
    - name: Setting up Redis
      run: docker run -p 6379:6379 -d --rm redislabs/rebloom:latest && docker ps -a
    - name: Running tests
      run: npm i && npm run redisbloom-topk-filter-tests
  #Build for 'Redis Bloom CMK' filter
  ReBloomCMK:
    needs: Setup
    if: (github.event_name == 'workflow_dispatch' && (contains(github.event.inputs.tests, 'rebloomCMK') || github.event.inputs.tests == 'All')) || github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
    - uses: docker-practice/actions-setup-docker@master
      with:
        docker_channel: nightly
        docker_nightly_version: snapshot-20200915
    - uses: actions/checkout@v2
    - name: Setting up Redis
      run: docker run -p 6379:6379 -d --rm redislabs/rebloom:latest && docker ps -a
    - name: Running tests
      run: npm i && npm run redisbloom-cmk-filter-tests
  #Build for 'Redis Bloom Cuckoo' filter
  ReBloomCuckoo:
    needs: Setup
    if: (github.event_name == 'workflow_dispatch' && (contains(github.event.inputs.tests, 'rebloomCuckoo') || github.event.inputs.tests == 'All')) || github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
    - uses: docker-practice/actions-setup-docker@master
      with:
        docker_channel: nightly
        docker_nightly_version: snapshot-20200915
    - uses: actions/checkout@v2
    - name: Setting up Redis
      run: docker run -p 6379:6379 -d --rm redislabs/rebloom:latest && docker ps -a
    - name: Running tests
      run: npm i && npm run redisbloom-cuckoo-filter-tests