# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  workflow_dispatch:
  push: 
    branches: [main]
  pull_request: 
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  ReJSON:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Installing Redis
        run: sudo apt update && sudo apt install make && sudo apt-get install build-essential && sudo apt-get install -y cargo && sudo apt install redis-server
      - name: Configurating Redis
        run: whoami && ls -l /etc/redis/redis.conf && sudo chown runner /etc/redis/redis.conf && sudo echo "supervised systemd" >> /etc/redis/redis.conf
      - name: Setting up Redis with ReJSON module
        run: sudo git clone https://github.com/RedisJSON/RedisJSON.git && cd RedisJSON && sudo cargo build --release && pwd && ls && sudo chmod -R 777 /etc/ && mkdir /etc/redis/modules/ && cd target && ls && mv librejson.so /etc/redis/modules/
        #run: sudo git clone https://github.com/RedisJSON/RedisJSON.git && cd RedisJSON && sudo apt-get install build-essential && sudo apt-get install -y cargo && sudo cargo build --release
      - name: Start Redis Server
        run: sudo echo "loadmodule /etc/redis/modules/librejson.so" >> /etc/redis/redis.conf && sudo /etc/init.d/redis-server stop sudo /etc/init.d/redis-server start
      - name: Redis status
        run: sudo systemctl status redis
      - name: Running tests
        run: npm i && npm run rejson-module-tests
