name: CI
on:
  workflow_dispatch:
  push: 
    branches: [master]
  pull_request: 
    branches: [master]

jobs:
  ReJSON:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Installing Redis
        run: sudo apt update && sudo apt install make && sudo apt-get install build-essential && sudo apt-get install -y cargo && sudo apt install redis-server 
      - name: Configurating Redis
        run: whoami && ls -l /etc/redis/redis.conf && sudo chown runner /etc/redis/redis.conf && sudo echo "supervised systemd" >> /etc/redis/redis.conf
      - name: Building ReJSON module
        run: sudo git clone https://github.com/RedisJSON/RedisJSON.git && cd RedisJSON && sudo cargo build --release && sudo mkdir /etc/redis/modules/ && sudo mv target/release/librejson.so /etc/redis/modules/
      - name: Restarting Redis Server
        run: sudo echo "loadmodule /etc/redis/modules/librejson.so" >> /etc/redis/redis.conf && sudo /etc/init.d/redis-server stop && sudo /etc/init.d/redis-server start
      - name: Verifying Redis status
        run: sudo systemctl status redis
      - name: Running tests
        run: npm i && npm run rejson-module-tests
  RediSearch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Installing Redis
        run: sudo apt update && sudo apt install make && sudo apt-get install build-essential && sudo apt-get install -y cargo && sudo apt install redis-server 
      - name: Configurating Redis
        run: whoami && ls -l /etc/redis/redis.conf && sudo chown runner /etc/redis/redis.conf && sudo echo "supervised systemd" >> /etc/redis/redis.conf
      - name: Building RediSearch module
        run: sudo git clone --recursive https://github.com/RediSearch/RediSearch.git && cd RediSearch && sudo make setup && sudo make fetch && sudo make build && sudo mkdir /etc/redis/modules/ && sudo mv build/redisearch.so /etc/redis/modules/ && cd /etc/redis/modules && ls
      - name: Restarting Redis Server
        run: sudo echo "loadmodule /etc/redis/modules/redisearch.so" >> /etc/redis/redis.conf && sudo redis-server stop && sudo redis-server start
      - name: Verifying Redis status
        run: sudo systemctl status redis
      - name: Running tests
        run: npm i && npm run rejson-module-tests
