name: CI
on:
  workflow_dispatch:
  push: 
    branches: [master]
  pull_request: 
    branches: [master]
jobs:
  #Build for 'ReJSON' module
  ReJSON:
    runs-on: ubuntu-latest
    steps:
    - uses: docker-practice/actions-setup-docker@master
      with:
        docker_channel: nightly
        docker_nightly_version: snapshot-20200915
    - uses: actions/checkout@v2
    - name:
      run: docker run -p 6379:6379 -d --rm redislabs/rejson:latest && docker ps -a
    - name: Running tests
      run: npm i && npm run rejson-module-tests
  #Build for 'Redis Times Series' module
  RTS:
    runs-on: ubuntu-latest
    steps:
    - uses: docker-practice/actions-setup-docker@master
      with:
        docker_channel: nightly
        docker_nightly_version: snapshot-20200915
    - uses: actions/checkout@v2
    - name:
      run: docker run -p 6379:6379 -d --rm redislabs/redistimeseries && docker ps -a
    - name: Running tests
      run: npm i && npm run rts-module-tests

